apiVersion: v1
kind: ConfigMap
metadata:
  name: initialother-backend-config
  namespace: initialother
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:mysql://initialother-mysql-service:3306/saifinance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  APP_CORS_ALLOWED_ORIGINS: http://localhost:8080,http://localhost:8081,http://localhost:5173,http://localhost:3000,http://initialother-ui.local