apiVersion: v1
kind: Service
metadata:
  name: initialother-kibana-service
  namespace: initialother
spec:
  type: NodePort
  selector:
    app: initialother-kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30601