apiVersion: v1
kind: Service
metadata:
  name: initialother-grafana-service
  namespace: initialother
spec:
  selector:
    app: initialother-grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP