apiVersion: apps/v1
kind: Deployment

metadata:
  name: initialother-grafana-deployment
  namespace: initialother

spec:
  replicas: 1

  selector:
    matchLabels:
      app: initialother-grafana

  template:
    metadata:
      labels:
        app: initialother-grafana

    spec:
      containers:
        - name: initialother-grafana

          image: grafana/grafana:latest

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin

          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana

            - name: grafana-datasource-config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml

            - name: grafana-dashboard-provider-config
              mountPath: /etc/grafana/provisioning/dashboards/dashboard-provider.yml
              subPath: dashboard-provider.yml

            - name: grafana-dashboard-config
              mountPath: /var/lib/grafana/dashboards/grafana-dashboard.json
              subPath: grafana-dashboard.json

          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"

            limits:
              memory: "256Mi"
              cpu: "200m"

      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: initialother-grafana-pvc

        - name: grafana-datasource-config
          configMap:
            name: initialother-grafana-datasource-config

        - name: grafana-dashboard-provider-config
          configMap:
            name: initialother-grafana-dashboard-provider-config

        - name: grafana-dashboard-config
          configMap:
            name: initialother-grafana-dashboard-config