apiVersion: v1
kind: ConfigMap
metadata:
  name: initialother-prometheus-config
  namespace: initialother
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "initialother-backend"
        metrics_path: "/api/v1/actuator/prometheus"
        static_configs:
          - targets:
              - "initialother-backend-service:8080"