apiVersion: apps/v1
kind: Deployment
metadata:
  name: initialother-prometheus-deployment
  namespace: initialother
spec:
  replicas: 1
  selector:
    matchLabels:
      app: initialother-prometheus
  template:
    metadata:
      labels:
        app: initialother-prometheus
    spec:
      containers:
        - name: initialother-prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: initialother-prometheus-config