apiVersion: apps/v1
kind: Deployment
metadata:
  name: initialother-rabbitmq-deployment
  namespace: initialother
spec:
  replicas: 1
  selector:
    matchLabels:
      app: initialother-rabbitmq
  template:
    metadata:
      labels:
        app: initialother-rabbitmq
    spec:
      containers:
        - name: initialother-rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management

          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: initialother-rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: initialother-rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS

          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq

          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 40
            periodSeconds: 20

      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: initialother-rabbitmq-pvc