apiVersion: v1
kind: ConfigMap
metadata:
  name: initialother-nginx-config
  namespace: initialother
data:
  default.conf: |
    server {
        listen 80;

        access_log /var/initialother/log/nginx/access.log;
        error_log  /var/initialother/log/nginx/error.log;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }