apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: initialother-frontend-logs-pvc
  namespace: initialother
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi